export declare const USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0";
export declare const REQ_HEADERS: {
    Accept: string;
    "Accept-Language": string;
    "User-Agent": string;
};
export declare const ANILIST_BASEURL = "https://graphql.anilist.co";
export declare const HIANIME_BASEURL = "https://hianimez.to";
export declare const ANIME_QUERY = "query ($id: Int) {\n  Media(id: $id, type: ANIME) {\n    id\n    idMal\n    title {\n      romaji\n      english\n      native\n      userPreferred\n    }\n    coverImage {\n      extraLarge\n      large\n      medium\n      color\n    }\n    format\n    description\n    genres\n    season\n    episodes\n    nextAiringEpisode {\n      id\n      timeUntilAiring\n      airingAt\n      episode\n    }\n    status\n    duration\n    seasonYear\n    bannerImage\n    favourites\n    popularity\n    averageScore\n    trailer {\n      id\n      site\n      thumbnail\n    }\n    startDate {\n      year\n      month\n      day\n    }\n    countryOfOrigin\n    recommendations(sort: RATING_DESC) {\n      edges {\n        node {\n          mediaRecommendation {\n            title {\n              romaji\n              english\n              native\n              userPreferred\n            }\n            format\n            coverImage {\n              extraLarge\n              large\n              medium\n              color\n            }\n          }\n        }\n      }\n    }\n    relations {\n      edges {\n        id\n        node {\n          title {\n            romaji\n            english\n            native\n            userPreferred\n          }\n          coverImage {\n            extraLarge\n            large\n            medium\n            color\n          }\n        }\n      }\n    }\n    characters(sort: FAVOURITES_DESC) {\n      edges {\n        role\n        node {\n          name {\n            first\n            middle\n            last\n            full\n            native\n            userPreferred\n          }\n          image {\n            large\n            medium\n          }\n        }\n        voiceActors(sort: FAVOURITES_DESC) {\n          name {\n            first\n            middle\n            last\n            full\n            native\n            userPreferred\n          }\n          image {\n            large\n            medium\n          }\n        }\n      }\n    }\n  }\n}\n";
